<script setup></script>
<template>
  <main>
    <h2>指令列表</h2>
    <p>本界面为抓小哥的帮助文档，以下每一指令后的括号内容表示其缩写，也可平替使用。在抓小哥帮助（zhuahelp）指令后接其他指令名，可展示对应指令的详细帮助哦。</p>
    <h3>游戏方式</h3>
    <ul>
      <li><com>抓小哥（zhua）</com>进行一次抓</li>
      <li><com>展示</com>展示小哥或皮肤的详细信息</li>
      <li><com>库存（kc）</com>展示个人仓库中的存量</li>
      <li><com>抓小哥进度（zhuajd）</com>展示目前收集的进度</li>
      <li><com>我的成就（mycj）</com>成就列表</li>
      <li><com>合成</com>消耗小哥和薯片进行合成</li>
      <li><com>小鹅猎场（xelc）</com>查看猎场界面</li>
    </ul>
    <h3>商店与皮肤</h3>
    <ul>
      <li><com>小镜商店（xjshop）</com>进入小镜的商店</li>
      <li><com>我有多少薯片（mysp）</com>告诉你你有多少薯片</li>
      <li><com>皮肤进度（pfjd）</com>展示目前收集小哥皮肤的进度</li>
      <li><com>切换皮肤</com>切换一个小哥的皮肤</li>
    </ul>
    <h3>日常信息</h3>
      <li><com>小镜签到（xjqd）</com>就是签个到而已</li>
      <li><com>小镜晚安</com>禁言到明天早上</li>
      <li><com>丢粑粑</com>尝试将自己的粑粑小哥丢给别人</li>
    <h3>其他信息</h3>
      <li><com>抓小哥帮助（zhuahelp）</com>显示这条帮助信息</li>
      <li><com>抓小哥更新（zhuagx）</com>显示抓小哥的更新信息</li>
      <li><com>关于小镜bot（kagamiabout）</com>查看小镜 Bot 服务器的信息</li>
  </main>
</template>